### ISSUE TITLE
能不能增加更方便的捐赠方法

### ISSUE THREAD

**Issue by kl135920** [BookShared/BookShared#1]
很乐意捐赠，但是捐赠太麻烦了

**Comment by BookShared** [comment]
> 很乐意捐赠，但是捐赠太麻烦了

没有其他更简单的方式了

**Comment by kl135920** [comment]
那能优化一下批量上传吗？一次性上传太多有的会掉

**Comment by BookShared** [comment]
> 那能优化一下批量上传吗？一次性上传太多有的会掉

目前由于网络问题容易导致连接超时，只能自己手动小批量上传，后续服务器和网络升级后就没有这个问题了
