### ISSUE TITLE
捐赠超过20u，为什么统计的时候只有11u？

### ISSUE THREAD

**Issue by LOVEMEBUT** [BookShared/BookShared#12]
难不成是有延迟？
![IMG_20231129_084258](https://github.com/BookShared/BookShared/assets/20140506/af05c6bd-46e9-40d9-9a63-8fd01e1440de)
![Screenshot_2023-11-29-08-37-42-874_com paxful wallet-edit](https://github.com/BookShared/BookShared/assets/20140506/1b38ab75-0fb7-430b-9f53-8d76ac3f0541)

**Comment by LOVEMEBUT** [comment]
劳烦作者看看转账对吗？

**Comment by BookShared** [comment]
马楼的命也是命啊，人需要休息的啊。看到后第一时间更新上去了
