### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by 3360891395** [BookShared/BookShared#23]
可以按照请求次数上限预载后面很多章的内容吗？
或者开放共享了的章节提前下载（限制一天内次数什么的）
目前服务器体验很差经常需要重启手机orAPP，我觉得这样会增加很多没必要的服务器请求

**Comment by 3360891395** [comment]
另，捐赠方式过于安全了，对国内环境不太友好。
唯一方便的币某安平台也需要个人信息认证

**Comment by TianXiaSky** [comment]
> 另，捐赠方式过于安全了，对国内环境不太友好。 唯一方便的币某安平台也需要个人信息认证

没办法，你要是放国内的收款码，直接给你投诉了。

**Comment by 3360891395** [comment]
> > 另，捐赠方式过于安全了，对国内环境不太友好。 唯一方便的币某安平台也需要个人信息认证
> 
> 没办法，你要是放国内的收款码，直接给你投诉了。

没办法，对抗版权太难了，还会有眼红的人

**Comment by ldp666** [comment]
捐赠方式劝退一些人😂

**Comment by LOVEMEBUT** [comment]
> 另，捐赠方式过于安全了，对国内环境不太友好。 唯一方便的币某安平台也需要个人信息认证

币安的认证也没什么，比支付宝，微信好多了，paxful的手续费很高

**Comment by 3360891395** [comment]
> > 另，捐赠方式过于安全了，对国内环境不太友好。 唯一方便的币某安平台也需要个人信息认证
> 
> 币安的认证也没什么，比支付宝，微信好多了，paxful的手续费很高

我很难随手找出来身份证（捂脸）
果然我还是正儿八经用隐私换便利的人

**Comment by 3360891395** [comment]
> > > 另，捐赠方式过于安全了，对国内环境不太友好。 唯一方便的币某安平台也需要个人信息认证
> > 
> > 
> > 币安的认证也没什么，比支付宝，微信好多了，paxful的手续费很高
> 
> 大佬，怎么注册币安呢

googleplay下载安装注册我用的邮箱
