### ISSUE TITLE
教程：切换cf节点

### ISSUE THREAD

**Issue by 3360891395** [BookShared/BookShared#25]
我的 页面 “长按” 左上角 设置 图标查看公告跳出来的弹窗左下角可以选择切换

我之前一头雾水直到我无聊想看看公告才发现在这里
readme里也没写在这里

**Comment by wushendutang** [comment]
但是长恩了也不能跳出来(苦恼)

**Comment by 3360891395** [comment]
> 之前长按设置可以跳出来，现在试了好多次都不行

因为服务器炸了还没修好

**Comment by 3360891395** [comment]
> > > > 但是长恩了也不能跳出来(苦恼)
> > > 
> > > 
> > > 是的，没跳出来，老哥，你的还能用不
> > 
> > 
> > 重启APP之后，按久一点，震动了再等一会
> 
> 我以为大陆节点弄好了，就在之前点击api更换到大陆节点了，现在长摁点不开公告了，无法切换api、试过重装模块、重启手机多次、清楚缓存(起点缓存、模块缓存)

因为服务器全炸了，现在好了你再试试

**Comment by BYNil9** [comment]
> > > > > 但是长恩了也不能跳出来(苦恼)
> > > > 
> > > > 
> > > > 是的，没跳出来，老哥，你的还能用不
> > > 
> > > 
> > > 重启APP之后，按久一点，震动了再等一会
> > 
> > 
> > 我以为大陆节点弄好了，就在之前点击api更换到大陆节点了，现在长摁点不开公告了，无法切换api、试过重装模块、重启手机多次、清楚缓存(起点缓存、模块缓存)
> 
> 因为服务器全炸了，现在好了你再试试

确实可以了

**Comment by 3360891395** [comment]
![Uploading IMG_20231208_011926.jpg…]()
