### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by vhfsb** [BookShared/BookShared#32]
感谢作者开发的程式，很厉害。

就是有些书好像买完后会跳到主屏幕，目录刷新有点慢，翻章节有些麻烦
![screenshot](https://github.com/BookShared/BookShared/assets/118702545/991da1ac-1260-4806-b558-b10d5234fede)

**Comment by Chen6708** [comment]
请问一下，是直接安装就可以嘛？然后打开起点读书app？不知道为什么没有反应。

**Comment by vhfsb** [comment]
就是买完一会 App 会退出，需要再点 App 进来

**Comment by 3360891395** [comment]
> 就是买完一会 App 会退出，需要再点 App 进来

是指订阅章节吗？我没问题，联系提供环境加log

**Comment by 3360891395** [comment]
> 看书显示未授权，你们有这情况吗

看明白readme就行

**Comment by hegong123** [comment]
不会用啊，怎么激活啊？我之前用老版的觉得还行，昨天更新后就不知道怎么用了，为什么新下载的安装包只有4.4MB啊

**Comment by hegong123** [comment]
> > 请问一下，是直接安装就可以嘛？然后打开起点读书app？不知道为什么没有反应。
> 
> 这是xp模块，激活即可使用

大佬，怎么激活啊？下载下来的sb不会用啊，我看好多激活软件都不支持安卓13了

**Comment by Chen6708** [comment]
我去查了一下，一开始没明白这是xp 模块，不好意思。 在网上了解到使用方法有多种，因为不太懂手机root ，我下载了太极，可是显示不支持。请问你们都是通过什么方式使用的？

**Comment by 3360891395** [comment]
> 我去查了一下，一开始没明白这是xp 模块，不好意思。 在网上了解到使用方法有多种，因为不太懂手机root ，我下载了太极，可是显示不支持。请问你们都是通过什么方式使用的？

可以使用lspatch

**Comment by 3360891395** [comment]
> > > 请问一下，是直接安装就可以嘛？然后打开起点读书app？不知道为什么没有反应。
> > 
> > 
> > 这是xp模块，激活即可使用
> 
> 大佬，怎么激活啊？下载下来的sb不会用啊，我看好多激活软件都不支持安卓13了

lspatch

**Comment by 3360891395** [comment]
> 不会用啊，怎么激活啊？我之前用老版的觉得还行，昨天更新后就不知道怎么用了，为什么新下载的安装包只有4.4MB啊

不应该啊，之前你都会用
