### ISSUE TITLE
来个人测试下捐赠，就最低的3块钱即可

### ISSUE THREAD

**Issue by BookShared** [BookShared/BookShared#34]
# 只需一个人，大家暂时别急着捐赠，有人成功后及时留

**Comment by 3360891395** [comment]
我来！

**Comment by 3360891395** [comment]
![Screenshot_2023-12-07-23-31-41-445_com tencent mm-edit](https://github.com/BookShared/BookShared/assets/32975424/bebb98f6-c2a7-41cc-9647-c600cddf05cf)
完事，是有手续费么

**Comment by BookShared** [comment]
> ![Screenshot_2023-12-07-23-31-41-445_com tencent mm-edit](https://private-user-images.githubusercontent.com/32975424/288808102-bebb98f6-c2a7-41cc-9647-c600cddf05cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NjM0NDksIm5iZiI6MTcwMTk2MzE0OSwicGF0aCI6Ii8zMjk3NTQyNC8yODg4MDgxMDItYmViYjk4ZjYtYzJhNy00MWNjLTk2NDctYzYwMGNkZGYwNWNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE1MzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZDYxOTA4NzE1YzkwZjk5OTFmYWVjMmI0NWFhOGQ4ZmI3MGJkMzJhZDlhZTNlYmQ3OGNlYjJlMzdlNTgxMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fO1vWyK0uQ0gCbXSCJxse3_VNeuy4V5wv-4qO_8psBI) 完事，是有手续费么

是的
