### ISSUE TITLE
全订阅了，但是没上传，上传有漏？

### ISSUE THREAD

**Issue by CatechumenLee** [BookShared/BookShared#49]
![微信图片_20231209134503](https://github.com/BookShared/BookShared/assets/47344165/a8e5d3a6-8451-4a19-bf92-bc4a4958aff7)

**Comment by Fridayfire** [comment]
sb是表示订阅了的吗，有些我看过的（共享的）也会显示未授权看不了

**Comment by BookShared** [comment]
> ![微信图片_20231209134503](https://private-user-images.githubusercontent.com/47344165/289236676-a8e5d3a6-8451-4a19-bf92-bc4a4958aff7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDIyOTMsIm5iZiI6MTcwMjEwMTk5MywicGF0aCI6Ii80NzM0NDE2NS8yODkyMzY2NzYtYThlNWQzYTYtODQ1MS00YTE5LWJmOTItYmM0YTQ5NThhZmY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA2MDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzUxYzU0MWQxYWFmY2FlMGY4YjNjMzdhODY4NzQzMmMyMDM1OWE5MTk2ZGIzMjIyZjEzOWY4ZjA5NTU3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DdqhJgGwQNOPqg2-AG4_6qve0HBQu3F5zvqX2j1PsMA)

漏掉的看项目文档清除缓存后用批量订阅选中没有标识的重新下载即可

**Comment by BookShared** [comment]
> sb是表示订阅了的吗，有些我看过的（共享的）也会显示未授权看不了

看明白项目文档你就知道为什么了

**Comment by Fridayfire** [comment]
谢谢大佬，是我没仔细看
