### ISSUE TITLE
目录哪里标识好棒！但是我又有问题了

### ISSUE THREAD

**Issue by wushendutang** [BookShared/BookShared#5]
能不能弄一个我们自己选择刷新上传、下载的恩键，免得我们一打开书他就查找，一打开目录就查找，查找还卡死，还经常浪费服务器资源(多次请求)
还有什么时候弄个，都有哪些书籍共享了的共享书架那种东西(名单)
这样好让我们一起看书、分享书

**Comment by BookShared** [comment]
卡死重启起点就行。服务器资源问题不大，主要是网络不太行，得看后续捐赠
