### ISSUE TITLE
如果多人上传能否剔除加的水印文字？

### ISSUE THREAD

**Issue by dv3lood** [BookShared/BookShared#54]
如[https://ngabbs.com/read.php?tid=31360365](https://ngabbs.com/read.php?tid=31360365)中说的，qd会在文章中修改你、在之类的文字来防盗，如果多人上传能否剔除这些信息防止用户被封号？

**Comment by BookShared** [comment]
理论上来说不用担心这个，因为模块是在数据解密阶段获取的数据。防盗替换那是在展示阶段的事，中间还差了好几个阶段
