### ISSUE TITLE
经常连不上打开连捐款页面都不弹出

### ISSUE THREAD

**Issue by kk1355315** [BookShared/BookShared#75]
更新完感觉更卡了

**Comment by darkadamaster** [comment]
![595f90b9f5bdf5fe69f2630839fc49f](https://github.com/BookShared/BookShared/assets/31944097/f4a321fd-ff56-4a52-a398-391cd24c8209)
经常性的这般模样，是服务器down了么？

**Comment by BookShared** [comment]
服务器还在维护中
