### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by david082321** [BookShared/BookShared#9]
LSPosed的日志(关键位置已打码)：`Connect timeout has expired [url=https://略:略/v1/content?bookId=略&chapterId=略, connect_timeout=unknown ms]`

IP位置：台湾

翻墙进入大陆可以正常使用。
請問能开放台湾ip使用吗？

**Comment by BookShared** [comment]
这是连接超时了，目前仅支持国内访问

**Comment by david082321** [comment]
> 目前仅支持国内访问

请问未来能否开放港澳台访问呢？

**Comment by BookShared** [comment]
> > 目前仅支持国内访问
> 
> 请问未来能否开放港澳台访问呢？

如果条件允许当然会
